import { ProductsProvider } from "@/context/products";
import { MyOrderProvider } from "@/context/myOrder";
// import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
import "./globals.css";

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
          <MyOrderProvider>
            <ProductsProvider>{children}</ProductsProvider>
          </MyOrderProvider>
      </body>
    </html>
  );
}
